#!/bin/bash

wha?() {
  aliases=(
      ~/.io/config/.aliases
      ~/.config/io/local_aliases
  )
  
  query() {
    printf '%s\n' ${aliases[@]}| \
     xargs -I % grep -n "$1" % | \
      sed -e 's/\s\+/ /'| \
       sed -e 's/\#/\n\#/'|
        grep ":\|$1\|#" --color=always
  
  #     for f in ${aliases[@]}
  #     do
  #         grep -n " $1" $f --color=auto | sed -e 's/\s\+/ /' | sed -e 's/\#/\n\#/'
  #     done
  
    exit
  }
  
  [[ $1 ]]&& query $1

#   if [ $1 ]
#   then
#       query $1
#   fi
  
  cat ~/.io/config/.aliases
}

wha? "$1"
