#!/bin/bash

aliases=(
    ~/.io/config/.aliases
    ~/.config/io/local_aliases
)

query() {
    for f in ${aliases[@]}
    do
        grep -n " $1" $f --color=auto | sed -e 's/\s\+/ /' | sed -e 's/\#/\n\#/'
    done
    exit
}


if [ $1 ]
then
    query $1
fi

nl ~/.io/config/.aliases | less
