#!/bin/bash

BIN=$(which brave)
[[ $BIN ]]|| BIN=$(which brave-browser)
[[ $(which tmux) ]] && tmux new-session -d -s Brave "$BIN $1" || \
  xfce4-terminal --tab -T Brave -e "$BIN $1"
#  printf "Brave not found\n"
