#!/bin/bash

BIN=$(which brave)
[[ $BIN ]]|| BIN=$(which brave)

check_session() {
  [[ $(tmux.ACT Process) ]] \
    && (send_session $1) \
    || (new_session $1)
}

new_session() {
    tmux new-session -ds Process $1
}

send_session() {
    tmux send -t Process "tmux split-pane -v $BIN" ENTER
}

check_session $BIN
