#!/bin/bash



while :
do
    echo "1. $Title"
    echo "Q. Quit"
    echo -n "Type 1 or 2 or Q :"

    read -n 1 -t 15 a

    printf "\n"

    case $a in
        $INDEX* )     $Case ;;
         
        q* )     exit 0;;

         
        * )     echo "Try again.";;
    esac

done
