#!/bin/bash

eval "$(/tmp/blks/set.VARS CGRAB `grabc`)"
echo $CGRAB|xclip -i -selection clipboard
result=`notify-send -h string:fgcolor:"#f3ebdc" -h string:bgcolor:"$CGRAB" 'Color Grab' "$CGRAB"`
printf $result|xclip -selection clipboard
