#!/bin/bash

input="$1"

export BLACK='\033[0;30m'
export BLUE='\033[0;34m'
export RUST='\033[0;33m'
export CYAN='\033[0;36m'
export DARK_GRAY='\033[1;30m'
export GREEN='\033[0;92m'
export LIGHT_BLUE='\033[1;34m'
export LIGHT_CYAN='\033[1;36m'
export LIGHT_GRAY='\033[0;37m'
export LIGHT_GREEN='\033[1;32m'
export LIGHT_PURPLE='\033[1;35m'
export PINK='\033[1;31m'
export PURPLE='\033[0;35m'
export RED='\033[0;31m'
export WHITE='\033[1;37m'
export YELLOW='\033[1;33m'
export NC='\033[0m'

# Expand bg
  export xBG="\e[K"

# Regular Colors
  export Bla="\e[0;30m"
  export Red="\e[0;31m"
  export Gre="\e[0;32m"
  export Yel="\e[0;33m"
  export Blu="\e[0;34m"
  export Pur="\e[0;35m"
  export Cya="\e[0;36m"
  export Whi="\e[0;37m"

# Bold Colors
  export dGra="\e[1m"
  export bBla="\e[1;30m"
  export bRed="\e[1;31m"
  export bGre="\e[1;32m"
  export bYel="\e[1;33m"
  export bBlu="\e[1;34m"
  export bPur="\e[1;35m"
  export bCya="\e[1;36m"
  export bWhi="\e[1;37m"

# Underlined Colors
  export uBla="\e[4;30m"
  export uRed="\e[4;31m"
  export uGre="\e[4;32m"
  export uYel="\e[4;33m"
  export uBlu="\e[4;34m"
  export uPur="\e[4;35m"
  export uCya="\e[4;36m"
  export uWhi="\e[4;37m"
  export uNoC="\e[4m"

# Colored Backgrounds
  export bgBla="\e[40m"
  export bgRed="\e[41m"
  export bgGre="\e[42m"
  export bgYel="\e[43m"
  export bgBlu="\e[44m"
  export bgPur="\e[45m"
  export bgCya="\e[46m"
  export bgWhi="\e[47m"

# High Intensity
  export hiBla="\e[0;90m"
  export hiRed="\e[0;91m"
  export hiGre="\e[0;92m"
  export hiYel="\e[0;93m"
  export hiBlu="\e[0;94m"
  export hiPur="\e[0;95m"
  export hiCya="\e[0;96m"
  export hiWhi="\e[0;97m"

# Bold High Intensity
  export bhiBla="\e[1;90m"
  export bhiRed="\e[1;91m"
  export bhiGre="\e[1;92m"
  export bhiYel="\e[1;93m"
  export bhiBlu="\e[1;94m"
  export bhiPur="\e[1;95m"
  export bhiCya="\e[1;96m"
  export bhiWhi="\e[1;97m"

# High Intensty backgrounds
  export hibgBla="\e[0;100m"
  export hibgRed="\e[0;101m"
  export hibgGre="\e[0;102m"
  export hibgYel="\e[0;103m"
  export hibgBlu="\e[0;104m"
  export hibgPur="\e[0;105m"
  export hibgCya="\e[0;106m"
  export hibgWhi="\e[0;107m"

#alias echo='echo -e'
#echo $GREEN"COLOR?"$NC

function color_usg() {
    printf "${YELLOW} USAGE:\n"
    printf '    printf ${RED}'"${RED}Red Text${YELLOW}"'${NC}\n '"${NC}\n"
    printf "${YELLOW}"
    printf '     Use ${NC} to change back to default or shell will stay that color!'"\n"
    printf '     color.SAMPLE will display color options.'"\n"
    /tmp/blks/color.SAMPLE
}

#### MASTER TABLE DO NOT EDIT SAVE TO UPDATE###
#Black        0;30     Dark Gray     1;30
#Red          0;31     Light Red     1;31
#Green        0;32     Light Green   1;32
#Brown/Orange 0;33     Yellow        1;33
#Blue         0;34     Light Blue    1;34
#Purple       0;35     Light Purple  1;35
#Cyan         0;36     Light Cyan    1;36
#Light Gray   0;37     White         1;37

# Based upon the following premise as direct quotations of :
#---------------------------------------------------------
# As Referenced on Aug 1, 2020 15:41 UTC
# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux

# answered May 10 '11 at 9:11
# Tobias
# 24.2k11 gold badge1616 silver badges23

##    .---------- constant part!
##    vvvv vvvv-- the code from above
#RED='\033[0;31m'
#NC='\033[0m' # No Color
#printf "I ${RED}love${NC} Stack Overflow\n"

# edited Jan 17 '19 at 1:44
# Daniel Compton
# 9,75933 gold badges3131 silver badges5353 bronze badges

# From @james-lim's comment, if you are using the echo command,
# be sure to use the -e flag to allow backslash escapes.

## Continued from above example
#echo -e "I ${RED}love${NC} Stack Overflow"
