#!/bin/bash

download() {
  case $# in
    1)
      url="$1"
      curl -o "/tmp/$(echo $url|awk -F '/' '{print $NF}')" -L $url
      ;;
    2)
      url="$1"
      name="$2"
      curl -o "$name" -L "$url"
      ;;
    *)
      url="$1"
      curl -o "/tmp/$(echo $url|awk -F '/' '{print $NF}')" -L $url ${@:1}
      ;;
  esac
}

download "$@"
