#!/bin/bash

[[ $# > 0 ]]|| ( ls -Ad "$PWD"/{*,.*}; exit )

while [[ "$#" -gt 0 ]]
do
  case $1 in
    -F)
      ls -AFd "$PWD"/{*,.*}
    ;;
    -l)
      ls -Ald "$PWD"/{*,.*}
    ;;
    *)
      ls -Ad "$PWD"/{*,.*}
    ;;
  esac
  shift
done
