#!/bin/bash

# Check if lolcat is installed
if [[ $(ruby -v 2>> /tmp/.0) ]]
then
    [[ $(which lolcat) ]] && \
        echo lolcat|lolcat \
      || echo sadcat
else
    echo deadcat
fi

# Cat laughs with rainbow if lolcat is installed!
# Cat is sad if ruby is in the path, but lolcat gem not installed
# Cat is dead if ruby is not installed in the path
