#!/bin/bash

case "$@" in
  *-l*)
    printf "alias $1='$2' # '$3'\n" >> $HOME/.config/io/local_aliases
    printf "alias $1 ceated, locally\n"
  ;;
  *)
    printf "alias $1='$2' # $3\n" >> ~/.io/config/.aliases
    printf "alias $1 ceated\n"
  ;;
esac
