#!/usr/bin/env ruby

load '/tmp/blks/replacer'

if ARGV.count < 3
  then puts "Usage: nnash <Host> <Name> <Key_Path>"
  exit 1
end

host = ARGV[0]
name = ARGV[1]
id   = ARGV[2]

arg = {
  "HOST": host,
  "ID": id,
  "NAME": name,
  "source": "~/.io/samples/ssh_blank",
  "dest": "~/.ssh/config.d/#{host}"
}

#cp ~/.io/samples/ssh_blank ~/.ssh/config.d/$1
#nano ~/.ssh/config.d/$1
