#!/bin/bash

source $HOME/.config/io/custom_path
PATH+=":/var/lib/flatpak/exports/share"
PATH+=":$HOME/.local/share/flatpak/exports/share"
PATH+=":/tmp/blks"
PATH+=":/snap/bin"
PATH+=":$HOME/bin"
PATH+=":/usr/local/pgsql/bin"
