#!/bin/bash

[[ -f ~/.local/bin/fns ]]&& source ~/.local/bin/fns
source $HOME/.config/io/custom_path
PATH+=":/var/lib/flatpak/exports/share"
PATH+=":$HOME/.local/share/flatpak/exports/share"
PATH+=":$HOME/.io/blanks"
PATH+=":/snap/bin"
PATH+=":$HOME/.bin"
