#!/bin/bash

purge_list() {
  LOG="/tmp/io/log/Purge"
  key_dir="$HOME/.io/blanks/keys"
  
  # Build the queue
  add.QUEUE "$@"
  
  # Switch chooses the correct installer to read the queue
  $(switch $key_dir/Purge)
}

purge_list "$@"
