#!/bin/bash

# sudo pacman -Rcn --noconfirm $1 #| lolcat
# Define constants
LOG="$HOME/.io/logs/Purge"
key_dir="/tmp/blks/keys"

# Build the queue
add.QUEUE "$@"

# Switch chooses the correct installer to read the queue
$(switch $key_dir/Purge)
