#!/bin/bash

function search () {
    TERM=("$@")
    OUTPUT=$(echo "~/$1" | cut -f1 -d ' ')
#    sudo find / |
 #    grep "${TERM[@]}" >>\
      echo $OUTPUT
      echo ${TERM[@]}
}

search "$1" &&\
echo searched || search ${1[@]}
###
# echo "~/$1" | cut -f1 -d ' ' 
# find / | grep "$1" >> $(echo "~/$1" | cut -f1 -d ' ')
