#!/bin/bash

setup_list() {
  # Define constants
  LOG="/tmp/io/log/Setup"
  key_dir="$HOME/.io/blanks/keys"
  
  # Build the queue
  add.QUEUE "$@"
  
  # Switch chooses the correct installer to read the queue
  $(switch $key_dir/Setup)
}

setup_list
