#!/bin/bash

# Define constants
LOG="$HOME/.io/logs/Setup"
key_dir="/tmp/blks/keys"

# Build the queue
add.QUEUE "$@"

# Switch chooses the correct installer to read the queue
$(switch $key_dir/Setup)
