#!/bin/bash

TARS=$(ls *.tar)
echo "$TARS to be updated and compressed for storage"
if[ ls *.tbz2 ];then 
    stored=$(ls *.tbz2)
    echo "$stored already are stored they will be updated if necessary"
else
    echo "archive has not stored a file here yet."
fi
