#!/bin/bash

tar -cjvfP ~/.defaults.tbz2 ~/.bashrc --remove-files
sudo tar -cjvfP - /etc/nanorc >> ~/.defaults.tbz2 --remove-files
echo "Default Bashrc and Nanorc Archived"
cp ~/.io/.bashrc ~/
sudo cp ~/.io/nanorc /etc/
echo "Bashrc and Nanorc Loaded from GitIOs"
