#!/bin/bash

index="1"
LIST_FILE="$HOME/.io/samples/Resources"
OUT_FILE="/data/wiki/LumpyspaceResList.html"
PATHS=()
QTY=$(cat $HOME/.io/samples/Resources | wc -l)
RESOURCES=()
TEMPLATE="$HOME/.io/samples/ResourceList.html"
#___________________________________________________VARIABLES DECLARED
listADD() {
    string=$1
    list=($@)
    i=0
    while [ $i -le ${#list[@]} ]
    do
        echo ${list[$i]} | grep -q / && \
        echo "            <p><a href=\"${PATHS[$i]//lumpyspace}\">${list[$i]}</a></p>" >> $OUT_FILE \
        ||\
         echo "            <p>${list[$i]}</p>"  >> $OUT_FILE
        ((i=$i+1))
    done
}
lineADD() {
    declare -i line=$1
    declare -i end=$2
    if [ ! $end ]
    then
        sed -n $1"p" $TEMPLATE  >> $OUT_FILE
    elif [ $end ]
    then
        index=$line
        while [ $index -le $end ]
        do
            sed -n $index"p" $TEMPLATE  >> $OUT_FILE
            index=$[ $index + 1 ]
        done
    else
        echo -e "${\033[0;31m}Strange end argument niether exists nor does not...${\033[0m}"
    fi
}
#____________________________________________________FUNCTIONS DEFINED
while [ $index -le $QTY ]
do
    RESOURCES+=($(
      sed -n $index"p" $LIST_FILE|
       cut -f1 -d ','
    ))
    PATHS+=($(
        sed -n $index"p" $LIST_FILE|
         cut -f2 -d ','
    ))
    index=$[ $index + 1 ]
done
#___________________________________________________ALL VARIABLES DEFINED
sudo \
 head -27 $TEMPLATE  > $OUT_FILE
#___________________________________________________RE-WRITES BODY CONTENT
listADD ${RESOURCES[@]}
#___________________________________________________FILL RESOURCE COLUMN
lineADD "29" "30"
#___________________________________________________COMPLETE RESOURCE COLUMN
listADD ${PATHS[@]}
#___________________________________________________FILL PATH COLUMN
lineADD "32" "36"
#___________________________________________________COMPLETE PATH COLUMN AND FOOTER
