#!/bin/bash

FILE="$1"

inv_browser() {
  tmux splitw -h -p 21 'nnn .'
  tmux select-pane -L
}

inv_editor() {
  tmux splitw -b -p 63 "nano $1"
  tmux select-pane -D
}

inv_gits() {
  
  tail -f /tmp/.git
#  tmux select-pane -U
}

tmux rename-window 'edit'
inv_browser
inv_editor $FILE
inv_gits
