#!/usr/bin/env ruby
# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name         =  NAME
  s.version      =  '0.0.0'
  s.summary      =  SUMMARY
  s.description  =  DESCRIPTION
  s.authors      =  AUTHORS
  s.email        =  EMAIL
  s.files        =  FILES
  s.homepage     =  'https://github.com/deftclaw'
  s.license      =  'MIT'
end
