# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# setCFG
#$HOME/.io/maint/io.CONFIG

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Navigate to path instead of responding no such command
shopt -s autocd

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]
then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

if [ -n "$force_color_prompt" ]
then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null
    then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

## Git BASH
# Load
source /tmp/blks/git-sh-prompt
# Config
GIT_PS1_SHOWDIRTYSTATE='true'
GIT_PS1_SHOWUPSTREAM='verbose'
GIT_PS1_SHOWCOLORHINTS='true'

# If custom ps1 is not detected use a basic one
if [ -f /tmp/ps1 ]
then
    source /tmp/ps1
else
    PS1='\u[$?]\h\w:$ '
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Add git prompt to PS1 when a repository is detected
[[ -s $HOME/.io/blanks/bash-git-prompt/gitprompt.sh ]]&& \
  GIT_PROMPT_ONLY_IN_REPO=1 && \
  git_ps1_colorize_gitstring=1 && \
  . $HOME/.io/blanks/bash-git-prompt

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]
then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -AF'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f $HOME/.io/config/.aliases ]
then
    alias setAl='source ~/.bashrc && sort.aliases'
    source $HOME/.io/config/.aliases
fi

# Source local_aliases if the exist
if [ -f $HOME/.config/io/local_aliases ]
then
    source $HOME/.config/io/local_aliases ]
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix
then
  if [ -f /usr/share/bash-completion/bash_completion ]
  then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]
  then
    . /etc/bash_completion
  fi
fi

# Hotkeys
source ~/.io/config/keybinds

# AutoJump
[[ $(which autojump 2>> /dev/null) ]] && source /usr/share/autojump/autojump.bash

# Path environment variable for spawning executables
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

  [[ -f $HOME/.io/.blanks/path+ ]] \
    && source $HOME/.io/.blanks/path+ \
    || printf "You may need to manually add PATH entries\n"
## End Path Mod

# Add asdf to Bash
[[ -d $HOME/.asdf ]]&& \
  source $HOME/.asdf/asdf.sh && source $HOME/.asdf/completions/asdf.bash

# Create disks file for neofetch to read all mounted disks
e=$(lsblk -o MOUNTPOINT|grep -v MOUNTPOINT|grep -v snap|grep -v SWAP|grep -v ^$)
rm /tmp/dskmnt &> /tmp/.0
for i in ${e[@]}
do
  printf "$i " >> /tmp/dskmnt
done

# NeoFetch
[[ $(which neofetch 2> /dev/null) ]] && /usr/bin/neofetch --color_blocks off &> /tmp/neofile & disown;
sleep 0.2

# Figlet
[[ $(which figlet) ]] && figlet -f smslant -w 130 '@'"$HOSTNAME"| lolcat -r -b
tail -n +1 /tmp/neofile

# Add .io/config/envar`s
if [ -f $HOME/.config/io/iorc ]
then
    source ~/.config/io/iorc
fi

[[ $(which direnv 2>> /dev/null) ]]&& eval "$(direnv hook bash)"
export PATH

source /tmp/ps1
export http_proxy=''
export https_proxy=''
export ftp_proxy=''
export socks_proxy=''
