# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]
then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]
then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null
    then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

## Git BASH
# Load
source $HOME/.io/blanks/git-sh-prompt
# Config
GIT_PS1_SHOWDIRTYSTATE='true'
GIT_PS1_SHOWUPSTREAM='verbose'
GIT_PS1_SHOWCOLORHINTS='true'

#[[ -f "$HOME/git/bash-git-prompt/gitprompt.sh" ]] && \
#  ( export GIT_PROMPT_ONLY_IN_REPO=1 && source "~/.bash-git-prompt/gitprompt.sh" ) || \
#  printf "Err.. check git prompt\n"

#if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]
#then
#    GIT_PROMPT_ONLY_IN_REPO=1
#    GIT_PROMPT_THEME=Single_line_Dark
#    source $HOME/.bash-git-prompt/gitprompt.sh
#fi

#if [ "$color_prompt" = yes ]
#then
#    PS1=$(cat $HOME/.io/config/PS1)
#else
#  	PS1=$(cat $HOME/.io/config/PS1)
#fi
#unset color_prompt force_color_prompt

if [ -f /tmp/ps1 ]
then
    source /tmp/ps1
else
    PS1='\u[$?]\h\w:$ '
fi

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

[[ -s $HOME/.io/blanks/bash-git-prompt/gitprompt.sh ]]&& \
  GIT_PROMPT_ONLY_IN_REPO=1 && \
  git_ps1_colorize_gitstring=1 && \
  . $HOME/.io/blanks/bash-git-prompt

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]
then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -AF'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.io/config/.aliases ]
then
    alias setAl='source ~/.bashrc'
    . ~/.io/config/.aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix
then
  if [ -f /usr/share/bash-completion/bash_completion ]
  then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]
  then
    . /etc/bash_completion
  fi
fi
alias setAl='sort.aliases && source ~/.bashrc'

# Figlet

source $HOME/.io/.blanks/color
printf "${LIGHT_GREEN}"
figlet -f smslant -w 130 "$USER"'@'"$HOSTNAME"
printf "${NC}"

## Start the SSH-Agent: Uncomment \ on 153 and all of 154 to enable default ~/.ssh/id_rsa
[ -z "$SSH_AUTH_SOCK" ]&& eval $(ssh-agent -s)
declare -a ssh_keys
[[ -s ~/.config/io/ssh.KEYS ]]&& source ~/.config/io/ssh.KEYS #\
#  || ln -s ~/.config/io/ssh.KEYS.sample ~/.config/io/ssh.KEYS
for k in "${ssh_keys[@]}"
do
    ssh-add "$k"
    d=$( echo $k|rev|cut -f1 -d /|rev )
    printf "added $d\n"
done
unset ssh_keys

# AutoJump
[[ -s /home/lij/.autojump/etc/profile.d/autojump.sh ]] && source /home/lij/.autojump/etc/profile.d/autojump.sh

# Path environment variable for spawning executables
  PATH=/usr/local/pgsql/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

  [[ -f $HOME/.io/.blanks/path+ ]] \
    && source $HOME/.io/.blanks/path+ \
    || printf "You may need to manually add PATH entries\n"
## End Path Mod

# NeoFetch
/usr/bin/neofetch --color_blocks off

# Add asdf to Bash
[[ -d $HOME/.asdf ]]&& \
  source $HOME/.asdf/asdf.sh && source $HOME/.asdf/completions/asdf.bash \
  || echo "asdf not installed"

# Add .io/config/envar`s
if [ -f $HOME/.io/config/envar ]
then
    . ~/.io/config/envar
fi

export PATH

# For some stupid git reason, adding git-sh-prompt made xterm default to /
#  So this stupid thing is here to start us back in $HOME
cd
