#!/bin/bash

io_help() {
  cat $HOME/.io/usg/main_help
}

io_configure() {
  $HOME/.io/maint/io.CONFIG
  source $HOME/.bashrc
}

back_to_basics() {
  cleanup=(
   "blks"
   "dskmnt"
   "neofile"
   "ps1"
  )
  rm $HOME/Downloads; mkdir $HOME/Downloads && mv /tmp/dwn/* $HOME/Downloads/
  for d in ${cleanup[@]}
  do
    rm -rv /tmp/$d
  done
  cp $HOME/.io/.default_profile.tbz2 $HOME/
  rm $HOME/.bashrc $HOME/.profile
  cd && tar -xjvf .default_profile.tbz2
}

[[ $# -eq 0 ]]&& io_help

#case "$opt" in
#  c)
#    $HOME/.io/maint/io.CONFIG
#    PS1='Configure'
#    source $HOME/.bashrc
#    ;;
#  *)
#    io_help
#    ;;
#esac

while [[ "$#" -gt 0 ]]
do
  case $1 in
    -c|--config|--configure)
      io_configure
      ;;
    -h|--help|\?)
      io_help
      ;;
    -u|--unload)
      back_to_basics
      ;;
    *)
      printf "${PINK}Unknown option: $1${NC}\n"
      io_help
      ;;
  esac
  shift
done
