#!/bin/bash

io_help() {
  cat $HOME/.io/usg/main_help
}

io_configure() {
  $HOME/.io/maint/io.CONFIG
  source $HOME/.bashrc
}

[[ $# -eq 0 ]]&& io_help

#case "$opt" in
#  c)
#    $HOME/.io/maint/io.CONFIG
#    PS1='Configure'
#    source $HOME/.bashrc
#    ;;
#  *)
#    io_help
#    ;;
#esac

while [[ "$#" -gt 0 ]]
do
  case $1 in
    -c|--config|--configure)
      io_configure
      ;;
    -h|--help|\?)
      io_help
      ;;
    *)
      printf "${PINK}Unknown option: $1${NC}\n"
      io_help
      ;;
  esac
  shift
done
